---
title: Percent Change in growth
author:
- M. Larsen^[Indiana University, Bloomington, IN]
abstract:
output: 
  pdf_document:
    fig_caption: yes
    keep_tex: no
    latex_engine: xelatex
    number_sections: no
geometry: margin=0.75in
editor_options: 
  chunk_output_type: console
---

```{r setup, include = F}
# Setup Work Environment
rm(list=ls())

library(pander)
library(tidyverse)

# document options
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.height = 4)

# load data
dat.perc <- read.csv("./raw_data/PercChange.csv",  header = T)
```

```{r PercChange}
p <- ggplot(data = dat.perc, aes(x = med.add, y = perc.change)) +
  #geom_point() + 
  stat_summary(fun.data = "mean_se", size = 1, bg = "white")+
  facet_grid(~ med.base) + 
  ylim(0,100)+
  theme_bw() +
  theme(panel.grid = element_blank(), 
        strip.background = element_blank()) +
  labs(x = "", y = "Change in growth (%)")
print(p)

#save figure
#ggsave(p, filename = "./supporting-files/FigureS1.tiff", dpi = 300, 
#       width = 5, height = 3, units = "in", scale = 1.1)
```

```{r stats}
dataN <- dat.perc[dat.perc$med.base=="NL", ]
dataP <- dat.perc[dat.perc$med.base=="PL", ]

pander(t.test(dataN[1:5, 3], dataN[6:10, 3],  alternative = "greater", 
              conf.level = 0.95, var.equal = TRUE), 
       caption = "t-test statistics for NL percent change in growth.",
       table.split.table = Inf)
pander(t.test(dataP[1:5, 3], dataP[6:10, 3],  alternative = "less", 
              conf.level = 0.95, var.equal = TRUE),
       caption = "t-test statistics for PL percent change in growth.")

```


